force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/ProjectStatus__c.field-meta.xml
<CustomField>
    <fullName>ProjectStatus__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inactive</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Target_Site_Stage__c.field-meta.xml
<CustomField>
    <fullName>Target_Site_Stage__c</fullName>
    <label>Target Site Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Protection &amp; Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Project_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Status__c</fullName>
    <label>Project Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Target_Site_Stage__c.field-meta.xml
<CustomField>
    <fullName>Target_Site_Stage__c</fullName>
    <label>Target Site Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Protection &amp; Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SiteVisitHelper.cls
public class SiteVisitHelper {
    public static void updateTargetSite(List<site_visit__c> triggernew,Map<Id,site_visit__c>oldMap){
        set<Id> leadIds = new Set<Id>();
        for(site_visit__c site : triggernew){
            if(site.Target_Site_Stage__c != null && (trigger.isInsert || site.Target_Site_Stage__c != oldMap.get(site.Id).Target_Site_Stage__c)){
                leadIds.add(site.Project__c);
            }
        } 
        if(!leadIds.isEmpty()){
            Map<Id,Lead__c> leadMap = new Map<Id,Lead__c>([select Id,Target_Site_Stage__c from Lead__c where id in :leadIds]);
            for(site_visit__c site : triggernew){
                if(site.Target_Site_Stage__c != null && (trigger.isInsert || site.Target_Site_Stage__c != oldMap.get(site.Id).Target_Site_Stage__c)){
                    Lead__c ld = leadMap.get(site.Project__c);
                    ld.Target_Site_Stage__c = site.Target_Site_Stage__c;
                    leadMap.put(site.Project__c,ld);
                }
            }
            update leadMap.values();
        }
        
    }
    public static void projectStatus(List<site_visit__c> triggernew,Map<Id,site_visit__c>oldMap){
        set<Id> leadIds = new Set<Id>();
        for(site_visit__c site : triggernew){
            if(site.Project_Status__c != null && (trigger.isInsert || site.Project_Status__c != oldMap.get(site.Id).Project_Status__c)){
                leadIds.add(site.Project__c);
            }
        } 
        if(!leadIds.isEmpty()){
            Map<Id,Lead__c> leadMap = new Map<Id,Lead__c>([select Id,ProjectStatus__c from Lead__c where id in :leadIds]);
            for(site_visit__c site : triggernew){
                if(site.Project_Status__c != null && (trigger.isInsert || site.Project_Status__c != oldMap.get(site.Id).Project_Status__c)){
                    Lead__c ld = leadMap.get(site.Project__c);
                    ld.ProjectStatus__c = site.Project_Status__c;
                    leadMap.put(site.Project__c,ld);
                }
            }
            update leadMap.values();
        }
    }
    public static void handleDelete(List<site_visit__c> triggernew,Map<Id,site_visit__c>oldMap){
        set<Id> leadIds = new Set<Id>();
        for(site_visit__c site : triggernew){
            if(site.Project_Status__c != null){
                leadIds.add(site.Project__c);
            }
        }
        if(!leadIds.isEmpty()){
            Map<Id,Lead__c> leadMap = new Map<Id,Lead__c>([select Id,ProjectStatus__c from Lead__c where id in :leadIds ]);
            for(site_visit__c site : triggernew){
                if(site.Project_Status__c != null && (trigger.isInsert || site.Project_Status__c != oldMap.get(site.Id).Project_Status__c)){
                    Lead__c ld = leadMap.get(site.Project__c);
                    ld.ProjectStatus__c = site.Project_Status__c;
                    leadMap.put(site.Project__c,ld);
                }
            }
            update leadMap.values();
        }
    }
}