force-app/main/default/objects/Lead/fields/ContactNumber__c.field-meta.xml
<CustomField>
    <fullName>ContactNumber__c</fullName>
    <label>ContactNumber</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Target_Site_Stage__c.field-meta.xml
<CustomField>
    <fullName>Target_Site_Stage__c</fullName>
    <label>Target Site Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Protection &amp; Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead__c/Lead__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Lead Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Lead__c/fields/ContactNumber__c.field-meta.xml
<CustomField>
    <fullName>ContactNumber__c</fullName>
    <label>Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Customer__c.field-meta.xml
<CustomField>
    <fullName>Customer__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead__c/fields/Target_Site_Stage__c.field-meta.xml
<CustomField>
    <fullName>Target_Site_Stage__c</fullName>
    <label>Target Site Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Protection &amp; Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity__c/Opportunity__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Order</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Customer Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity__c.RecordType.Name</field>
            <operation>equals</operation>
            <value>Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity__c</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Primary_contact__c.field-meta.xml
<CustomField>
    <fullName>Primary_contact__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Primary contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.Account_Name__c</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Opportunities</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/Site_Visit__c.object-meta.xml
<CustomObject>
    <label>Site Visit</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Site Visit Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Site Visits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Site_Visit__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project</label>
    <referenceTo>Lead__c</referenceTo>
    <relationshipLabel>Site Visits</relationshipLabel>
    <relationshipName>Site_Visits</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Site_Visit__c/fields/Target_Site_Stage__c.field-meta.xml
<CustomField>
    <fullName>Target_Site_Stage__c</fullName>
    <label>Target Site Stage</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Installation</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Protection &amp; Maintenance</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlaceOrderController.cls
public class PlaceOrderController {
    
    @AuraEnabled
    public static String queryData(Id recordId){
        Set<Id> accId = new Set<Id>();
        list<Account> accList = new  list<Account>();
        Opportunity__c opp = new Opportunity__c();
        List<Lead__c> leadList =[select id,Email__c,ContactNumber__c, Name,FirstName__c, LastName__c,Company__c,Customer__c   from Lead__c where id=:recordId];
        //List<contact> con =[select id,AccountId,Account.Name from Contact where Email =:lead.Email__c];
        for(Lead__c leadObj : leadList){
            if(leadObj.Customer__c != null){
                accId.add(leadObj.Customer__c);
            }
            else if(leadObj.Customer__c == null){
                Account custObj = new Account();
                custObj.Name =leadObj.Company__c;
                accList.add(custObj);
            }
        }
        if(!accList.isEmpty()){
            insert accList;
            contact con = new contact(LastName=leadList[0].Name,AccountId=accList[0].Id,Email=leadList[0].Email__c);
            insert con;
            opp.Close_Date__c=system.today()+7;
            opp.Name=accList[0].Name;
            opp.Primary_contact__c=con.Id;
            opp.RecordTypeId='0121m000000DsT8AAK';
            opp.Account_Name__c=accList[0].Id;
            opp.Project__c=recordId;
            insert opp;
        }
        if(!accId.isEmpty()){
            list <Account> newList = [select id,Name from Account where id in :accId];
            contact con=[select id from contact where id = :newList[0].Id];
            opp.Close_Date__c=system.today()+7;
            opp.Name=newList[0].Name;
            opp.Primary_contact__c=con.Id;
            opp.RecordTypeId='0121m000000DsT8AAK';
            opp.Account_Name__c=newList[0].Id;
            opp.Project__c=recordId;
            insert opp;
            
            
        }
       
        
        return opp.Id;
    }
        @AuraEnabled
    public static string saveSite(Id recordId){
            
        Site_Visit__c sv= new Site_Visit__c();
        sv.Project__c=recordId;
        sv.Target_Site_Stage__c='Installation';
        sv.Date__c=system.today();
        insert sv;
            
        
        return sv.Id;
        
        
    }
}